[versions]
kotlin = "2.1.0"
shadow = "8.1.1"
mordant = "3.0.2"

[libraries]
mordant-core = { group = "com.github.ajalt.mordant", name = "mordant", version.ref = "mordant"}
mordant-coroutines = { group = "com.github.ajalt.mordant", name = "mordant-coroutines", version.ref = "mordant"}

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }

[bundles]
mordant = ["mordant-core", "mordant-coroutines"]